# Generated by Django 5.2.6 on 2025-09-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_contactform"),
    ]

    operations = [
        migrations.AddField(
            model_name="flan",
            name="price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
